name: huntsphere
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  supabase_flutter: ^2.5.6
  google_fonts: ^6.2.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.5
  image_picker: ^1.0.7
  camera: ^0.11.0+2
  
  # GPS & Map Dependencies
  google_maps_flutter: ^2.5.0
  google_maps_flutter_web: ^0.5.4+2
  geolocator: ^11.0.0
  geocoding: ^3.0.0
  
  # QR Code
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.0.0
  
  # Utilities
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
